variables:
  SOPLEX_REVISION: release-700
  SCIP_REVISION: v900
  BOOST_VERSION: 1.65.0

stages:
  - test

.ctest:
  stage: test
  image:
    name: gcc:10
  tags:
    - compile
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  before_script:
    - apt-get update
    - apt-get install -y cmake libtbb-dev libblas-dev
  script:
    # download, build and install boost
    - wget https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/boost_$(echo ${BOOST_VERSION} | tr . _).tar.gz
    - tar -xzf boost_$(echo ${BOOST_VERSION} | tr . _).tar.gz
    - cd boost_$(echo ${BOOST_VERSION} | tr . _)
    - ./bootstrap.sh --with-libraries=program_options,serialization,iostreams,regex
    - ./b2 -j6 install

    # clone, build and install soplex
    - git clone https://github.com/scipopt/soplex.git ${CI_PROJECT_DIR}/soplex
    - cd ${CI_PROJECT_DIR}/soplex && git checkout ${SOPLEX_REVISION}
    - mkdir $CI_PROJECT_DIR/soplex-build
    - cd $CI_PROJECT_DIR/soplex-build
    - cmake $CI_PROJECT_DIR/soplex -DCMAKE_BUILD_TYPE=Release
    - make -j && make install

    # clone, build and install scip
    - git clone https://github.com/scipopt/scip.git ${CI_PROJECT_DIR}/scip
    - cd ${CI_PROJECT_DIR}/scip && git checkout ${SCIP_REVISION}
    - mkdir -p $CI_PROJECT_DIR/scip-build
    - cd $CI_PROJECT_DIR/scip-build
    - cmake $CI_PROJECT_DIR/scip -DCMAKE_BUILD_TYPE=Release -DZIMPL=off -DREADLINE=off -DGMP=off -DPAPILO=off -DIPOPT=off
    - make -j && make install

    # build and test papilo
    - mkdir -p $CI_PROJECT_DIR/builds/papilo
    - cd $CI_PROJECT_DIR/builds/papilo
    - export CFLAGS="-Werror"
    - export CXXFLAGS="-Werror"
    - cmake $CI_PROJECT_DIR ${CMAKE_FLAGS} -DBLA_STATIC=ON
    - make -j6
    - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
    - ctest -j --output-on-failure

"ctest release":
  extends: .ctest
  variables:
    CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Release"

"ctest release notbb":
  extends: .ctest
  variables:
    CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Release -DTBB=off"

"ctest debug":
  extends: .ctest
  variables:
    CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Debug"

".scip test":
  stage: test
  image:
    name: gcc:10
  tags:
    - compile
  before_script:
    - apt-get update
    - apt-get install -y cmake libtbb-dev libblas-dev libcriterion-dev
  script:
    # download, build and install boost
    - wget https://boostorg.jfrog.io/artifactory/main/release/${BOOST_VERSION}/source/boost_$(echo ${BOOST_VERSION} | tr . _).tar.gz
    - tar -xzf boost_$(echo ${BOOST_VERSION} | tr . _).tar.gz
    - cd boost_$(echo ${BOOST_VERSION} | tr . _)
    - ./bootstrap.sh --with-libraries=program_options,serialization,iostreams,regex
    - ./b2 -j6 install

    # build and install papilo
    - mkdir -p $CI_PROJECT_DIR/builds/papilo
    - cd $CI_PROJECT_DIR/builds/papilo
    - export CFLAGS="-Werror"
    - export CXXFLAGS="-Werror"
    - cmake $CI_PROJECT_DIR ${CMAKE_FLAGS} -DBLA_STATIC=ON
    - make -j6
    - make install

    # clone, build and install soplex
    - git clone https://github.com/scipopt/soplex.git ${CI_PROJECT_DIR}/soplex
    - cd ${CI_PROJECT_DIR}/soplex && git checkout ${SOPLEX_REVISION}
    - mkdir $CI_PROJECT_DIR/soplex-build
    - cd $CI_PROJECT_DIR/soplex-build
    - cmake $CI_PROJECT_DIR/soplex -DCMAKE_BUILD_TYPE=Release
    - make -j && make install

    # clone, build and install scip
    - git clone https://github.com/scipopt/scip.git ${CI_PROJECT_DIR}/scip
    - cd ${CI_PROJECT_DIR}/scip && git checkout ${SCIP_REVISION}
    - mkdir -p $CI_PROJECT_DIR/scip-build
    - cd $CI_PROJECT_DIR/scip-build
    - cmake $CI_PROJECT_DIR/scip ${CMAKE_FLAGS} -DZIMPL=off -DREADLINE=off -DGMP=off -DIPOPT=off
    - make -j && make install
    - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
    - ctest -j --output-on-failure

"scip test":
  extends: .scip test
  variables:
    CMAKE_FLAGS: "-DCMAKE_BUILD_TYPE=Debug"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
